services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LinkORB\Bundle\WikiBundle\:
    resource: '../src/*'

  LinkORB\Bundle\WikiBundle\AccessControl\EvalInterface:
    alias: LinkORB\Bundle\WikiBundle\AccessControl\IsGrantedEval
